### ISSUE TITLE
problem with php8.2

### ISSUE THREAD

**Issue by einseinsvier-web** [gregorionuti/Joomla-Digi-Showcase#5]
Hi,
when using digi showcase with joomla 5.2. and php 8.2 this error appears when errorreporting is set to maximum:
PHP Deprecated:  Creation of dynamic property Digi_Showcase_Helper::$data_filter is deprecated in /.../modules/mod_digi_showcase/helper.php on line 72

Is this a problem of php 8.2?
thanks for helping

**Comment by gregorionuti** [comment]
Hello, thanks for the report.

It's a warning and not an error, it's related to the deprecation of dynamic properties in PHP 8.2 as reported here https://php.watch/versions/8.2/dynamic-properties-deprecated so in older version of PHP this warning should disappear.

For now just ignore it, the module should work fine. As well as I suppose you are not keeping error reporting to maximum on your production website. I mark down the issue, I will check it out in the next releases, trying to keep the module compatible with PHP 7.0+ and 8.0+ then Joomla 3+ and Joomla 5+

**Comment by einseinsvier-web** [comment]
Thanks for the feedback.
