### ISSUE TITLE
De module in my homepage gives a Devision by zero

### ISSUE THREAD

**Issue by Bvdveen12** [gregorionuti/Joomla-Digi-Showcase#6]
With only a text arikle there is no problem. When I add a image to the intro text there is no homepage just error message. 
![DevideByZereo](https://github.com/user-attachments/assets/0bd7d520-8fa4-4018-8a3e-e875dc5f67a9)

Hope there is a solusion. 

See: https://www.christelijkmannenkoorbeilen.nl/
Regards,
Bé van der Veen

**Comment by Bvdveen12** [comment]
I used a normal JPG image. With other images no problem. 
So I made schreen shot of the image in Photoshop. With the schreenshot image there was no problem.
My question is now: what are the limitations for the use images? 
Thanks.
Bé van der Veen. 
See: www.christelijkmannenkoorbeilen.nl

**Comment by gregorionuti** [comment]
Hello, you may try to disable "generate thumbnails" option under "items" tab in Digi Showcase control panel. It may be a problem related to some missing libraries in your server. By doing that, the origina article image will be used as item image in the module, without further modifications (no resizing, no thumbnails creation). This solution should solve the problem, is it still persist.

Normally jpg and png images should work, except that there is no transparency in thumbnails generated from png images.

Kind regards,
Greg
